name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  security-and-build:
    runs-on: ubuntu-latest

    steps:

    # ---------------- CHECKOUT CODE ----------------
    - name: Checkout Code
      uses: actions/checkout@v3

    # ---------------- SETUP PYTHON ----------------
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # ---------------- INSTALL DEPENDENCIES ----------------
    - name: Install Dependencies
      run: |
        pip install -r app/requirements.txt

    # ---------------- SAST SCAN (SEMGREP) ----------------
    - name: Run SAST Scan (Semgrep)
      run: |
        pip install semgrep
        semgrep scan app/ --config auto --json --output semgrep-report.json || true

    - name: Show Semgrep Results
      run: cat semgrep-report.json

    # ---------------- SECRET SCAN (GITLEAKS) ----------------
    - name: Run Gitleaks Secret Scan
      uses: gitleaks/gitleaks-action@v2
      continue-on-error: true

    # ---------------- POLICY GATE ----------------
    - name: Fail if Fake Secret Exists
      run: |
        if grep -r "AWS_SECRET_ACCESS_KEY" app/; then
          echo "SECRET DETECTED - FAILING PIPELINE"
          exit 1
        fi

    # ---------------- DOCKER BUILD ----------------
    - name: Build Docker Image
      run: |
        cd app
        docker build -t devsecops-app .

    # ---------------- IaC SCAN (CHECKOV) ----------------
    - name: Run Checkov IaC Scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform/
        soft_fail: true
    # ---------------- AWS AUTH ----------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    # ---------------- TERRAFORM ----------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan

    # ---------------- CONTAINER SCAN (TRIVY) ----------------
    - name: Run Trivy Container Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'devsecops-app'
      continue-on-error: true

    # ---------------- CD PIPELINE (SIMULATED) ----------------

    # ---------------- DEPLOY DEV ----------------
    - name: Deploy to Dev
      run: |
        echo "Deploying to DEV"
        export ENV=dev
        export PORT=5001
        nohup python3 app.py &

    # ---------------- DEPLOY STAGING ----------------
    - name: Deploy to Staging
      run: |
        echo "Deploying to STAGING"
        export ENV=staging
        export PORT=5002
         nohup python3 app.py &

    # ---------------- DEPLOY PROD ----------------
    - name: Deploy to Production
      run: |
        echo "Deploying to PROD"
        export ENV=prod
        export PORT=5003
        nohup python3 app.py &
