name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  security-and-build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r app/requirements.txt

    # SECRET SCAN
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2

    # POLICY GATE
    - name: Fail if Fake Secret Exists
      run: |
        if grep -r "AWS_SECRET_ACCESS_KEY" app/; then
          echo "SECRET DETECTED - FAILING PIPELINE"
          exit 1
        fi

    # BUILD IMAGE
    - name: Build Docker Image
      run: |
        cd app
        docker build -t devsecops-app .

    # IaC SCAN
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform/
        soft_fail: true

    # TERRAFORM SETUP
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # AWS LOGIN
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # TERRAFORM INIT
    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    # TERRAFORM VALIDATE
    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    # TERRAFORM APPLY
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve

    # CONTAINER SCAN
    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'devsecops'

    # DEV
    - name: Deploy to Dev
      run: |
        export ENV=dev
        export PORT=5001
        nohup python3 app.py &

    # STAGING
    - name: Deploy to Staging
      run: |
        export ENV=staging
        export PORT=5002
        nohup python3 app.py &

    # PROD
    - name: Deploy to Production
    run: |
      export ENV=prod
      export PORT=5003
      nohup python3 app.py &
